/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:f3c4e8c3-fb07-4c61-bddf-a048df77fcb3",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_qa5NZ5FuF",
    "aws_user_pools_web_client_id": "6413aj6rg3gmhu86r668vnu4q3",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "aws-lazy-images-gallery135804-staging",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
